adapter_name_or_path: saves/Qwen2.5-1.5B-Instruct/lora/train_2025-03-31-16-28-44-1.5b-task1-lora-4lun-2500jieduan-eval0.111
cutoff_len: 2500
dataset_dir: /root/ambem_distill_03_task1
do_predict: true
eval_dataset: eval
finetuning_type: lora
flash_attn: auto
max_new_tokens: 8192
max_samples: 100000
model_name_or_path: /root/autodl-tmp/modelscope/hub/Qwen/Qwen2.5-1.5B-Instruct/
output_dir: saves/Qwen2.5-1.5B-Instruct/lora/eval_2025-04-09-10-12-08-1.5b-task1-lora-4lun-2500jieduan-eval0.111
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
temperature: 0.1
template: qwen
top_p: 0.7
trust_remote_code: true
