eval.batch_size: 2
eval.cutoff_len: 4500
eval.dataset:
- eval
eval.dataset_dir: /root/ambem_distill_03_task3
eval.max_new_tokens: 8192
eval.max_samples: '100000'
eval.output_dir: eval_2025-04-08-16-56-41-3b-task3-lora-4lun-4500jieduan
eval.predict: true
eval.temperature: 0.1
eval.top_p: 0.7
top.booster: auto
top.checkpoint_path:
- train_2025-03-30-20-23-07-3b-task3-lora-4lun-4500jieduan-eval0.111
top.finetuning_type: lora
top.model_name: Qwen2.5-3B-Instruct
top.quantization_bit: none
top.quantization_method: bitsandbytes
top.rope_scaling: none
top.template: qwen
