adapter_name_or_path: saves/Llama-3.1-8B-Instruct/lora/train_2026-06-22-19-52-55-8b-lora-4lun-6500jieduan-eval0.111
cutoff_len: 6500
dataset_dir: /root/ambem_distill_03
do_predict: true
eval_dataset: eval
finetuning_type: lora
flash_attn: auto
max_new_tokens: 8192
max_samples: 100000
model_name_or_path: /root/autodl-tmp/modelscope/hub/LLM-Research/Meta-Llama-3.1-8B-Instruct
output_dir: saves/Llama-3.1-8B-Instruct/lora/eval_2026-06-22-19-52-55-8b-lora-4lun-6500jieduan-eval0.111
per_device_eval_batch_size: 2
predict_with_generate: true
preprocessing_num_workers: 16
quantization_method: bitsandbytes
stage: sft
temperature: 0.1
template: llama3
top_p: 0.7
trust_remote_code: true
